### PR TITLE
add Krio to list of languages

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?164010

### CODE REVIEW

**Comment by czue** [comment]
@dannyroberts out of curiosity, where did you pull this list from initially? this is the first language i've seen missing

**Comment by czue** [comment]
(up for grab)

**Comment by dannyroberts** [comment]
I pulled it from one of these downloads: http://www-01.sil.org/iso639-3/download.asp (or some very similar page 4 years ago). These get updated every few years, so the only thing I can think is that it was a recent addition

**Comment by dannyroberts** [comment]
I also definitely did some processing on those files to get it in json format, and then almost certainly threw away the script as if I'd never have to do it again

**Pull request merged**
